#!/usr/bin/env node
/**
 * verify-env.js
 * Environment Manifest Verification Script
 *
 * Generated by the Complete Development Handbook Bootstrap.
 * Run before any deployment or cloud operation.
 *
 * Usage:
 *   node scripts/verify-env.js [environment]
 *   node scripts/verify-env.js local
 *   node scripts/verify-env.js staging
 *   node scripts/verify-env.js production
 *
 * Environment is also read from:
 *   NODE_ENV, VITE_ENV, NEXT_PUBLIC_ENV, FLUTTER_ENV
 */

'use strict';

const fs = require('fs');
const path = require('path');

// ─── Colours for terminal output ───────────────────────────────────────────
const c = {
  reset: '\x1b[0m',
  red: '\x1b[31m',
  green: '\x1b[32m',
  yellow: '\x1b[33m',
  blue: '\x1b[34m',
  bold: '\x1b[1m',
  dim: '\x1b[2m',
};

function pass(msg) { console.log(`  ${c.green}✓${c.reset} ${msg}`); }
function fail(msg) { console.error(`  ${c.red}✗${c.reset} ${c.bold}${msg}${c.reset}`); }
function warn(msg) { console.warn(`  ${c.yellow}⚠${c.reset} ${msg}`); }
function info(msg) { console.log(`  ${c.blue}→${c.reset} ${msg}`); }
function section(msg) { console.log(`\n${c.bold}${msg}${c.reset}`); }

// ─── Load manifest ──────────────────────────────────────────────────────────
const manifestPath = path.join(process.cwd(), '.env.manifest');

if (!fs.existsSync(manifestPath)) {
  fail('.env.manifest not found in project root.');
  console.error(`  Expected at: ${manifestPath}`);
  console.error(`  Run the Handbook Bootstrap to generate it.`);
  process.exit(1);
}

let manifest;
try {
  manifest = JSON.parse(fs.readFileSync(manifestPath, 'utf8'));
} catch (err) {
  fail(`.env.manifest is not valid JSON: ${err.message}`);
  process.exit(1);
}

// ─── Determine target environment ──────────────────────────────────────────
const targetEnv = (
  process.argv[2] ||
  process.env.NODE_ENV ||
  process.env.NEXT_PUBLIC_ENV ||
  process.env.VITE_ENV ||
  process.env.FLUTTER_ENV ||
  'local'
).toLowerCase().replace('development', 'local');

section(`Environment Verification — ${manifest._meta?.project_name || 'Unknown Project'}`);
info(`Manifest version: ${manifest._meta?.manifest_version || 'unknown'}`);
info(`Target environment: ${c.bold}${targetEnv}${c.reset}`);

// ─── Validate environment exists ───────────────────────────────────────────
const validEnvironments = Object.keys(manifest.environments || {});
if (!validEnvironments.includes(targetEnv)) {
  fail(`Unknown environment: "${targetEnv}"`);
  console.error(`  Valid environments: ${validEnvironments.join(', ')}`);
  process.exit(1);
}

const env = manifest.environments[targetEnv];
let errorCount = 0;
let warningCount = 0;

// ─── Firebase verification ─────────────────────────────────────────────────
if (env.firebase) {
  section('Firebase');
  
  // Check runtime env vars match manifest
  const checks = [
    ['NEXT_PUBLIC_FIREBASE_PROJECT_ID', env.firebase.projectId],
    ['VITE_FIREBASE_PROJECT_ID', env.firebase.projectId],
    ['FIREBASE_PROJECT_ID', env.firebase.projectId],
    ['NEXT_PUBLIC_FIREBASE_APP_ID', env.firebase.appId],
    ['VITE_FIREBASE_APP_ID', env.firebase.appId],
  ];

  let firebaseChecked = false;
  for (const [envVar, expectedValue] of checks) {
    const runtimeValue = process.env[envVar];
    if (runtimeValue) {
      firebaseChecked = true;
      if (runtimeValue !== expectedValue) {
        fail(`${envVar} MISMATCH`);
        console.error(`    Manifest expects: ${c.bold}${expectedValue}${c.reset}`);
        console.error(`    Runtime has:      ${c.red}${runtimeValue}${c.reset}`);
        errorCount++;
      } else {
        pass(`${envVar} matches manifest (${expectedValue})`);
      }
    }
  }

  if (!firebaseChecked) {
    info('Firebase env vars not found at runtime (may be set elsewhere)');
    info(`Manifest project ID: ${env.firebase.projectId}`);
  }

  // Sanity check: staging/prod project IDs should be different
  if (targetEnv === 'production' && manifest.environments.staging) {
    const stagingId = manifest.environments.staging.firebase?.projectId;
    if (stagingId && stagingId === env.firebase.projectId) {
      fail('Production and staging Firebase project IDs are IDENTICAL');
      console.error('  This means production and staging share the same database.');
      console.error('  This is almost certainly wrong. Verify with the human.');
      errorCount++;
    } else if (stagingId) {
      pass('Production Firebase project is different from staging');
    }
  }
}

// ─── Supabase verification ─────────────────────────────────────────────────
if (env.supabase) {
  section('Supabase');
  
  const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL || process.env.VITE_SUPABASE_URL;
  if (supabaseUrl) {
    const refFromUrl = supabaseUrl.match(/https:\/\/([^.]+)\.supabase\.co/)?.[1];
    if (refFromUrl && refFromUrl !== env.supabase.projectRef) {
      fail('Supabase project ref MISMATCH');
      console.error(`  Manifest expects: ${env.supabase.projectRef}`);
      console.error(`  URL contains:     ${refFromUrl}`);
      errorCount++;
    } else if (refFromUrl) {
      pass(`Supabase project ref matches (${env.supabase.projectRef})`);
    }
  } else {
    info(`Supabase project ref from manifest: ${env.supabase.projectRef}`);
  }
}

// ─── Stripe verification ───────────────────────────────────────────────────
if (env.stripe) {
  section('Stripe');
  
  const stripeKey = process.env.STRIPE_SECRET_KEY || process.env.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY;
  if (stripeKey) {
    const isTestKey = stripeKey.includes('_test_');
    const isLiveKey = stripeKey.includes('_live_');
    const expectedMode = env.stripe.mode;

    if (expectedMode === 'live' && isTestKey) {
      fail(`Production Stripe mode expected but TEST key is set`);
      console.error('  A test key cannot process real payments.');
      errorCount++;
    } else if (expectedMode === 'test' && isLiveKey) {
      fail(`Test/staging environment but LIVE Stripe key is set`);
      console.error('  This will charge real money in a test environment.');
      console.error('  This is a critical misconfiguration. Stop immediately.');
      errorCount++;
    } else if (expectedMode === 'live' && isLiveKey) {
      pass(`Stripe live mode confirmed`);
    } else if (expectedMode === 'test' && isTestKey) {
      pass(`Stripe test mode confirmed`);
    }
  } else {
    info(`Stripe mode from manifest: ${env.stripe.mode}`);
  }
}

// ─── Vercel verification ───────────────────────────────────────────────────
if (env.vercel) {
  section('Vercel');
  
  const vercelProjectId = process.env.VERCEL_PROJECT_ID;
  if (vercelProjectId && vercelProjectId !== env.vercel.projectId) {
    warn(`VERCEL_PROJECT_ID does not match manifest`);
    console.warn(`  Manifest: ${env.vercel.projectId}`);
    console.warn(`  Runtime:  ${vercelProjectId}`);
    warningCount++;
  } else if (vercelProjectId) {
    pass(`Vercel project ID matches`);
  } else {
    info(`Vercel project ID from manifest: ${env.vercel.projectId}`);
  }
}

// ─── Production guards ─────────────────────────────────────────────────────
if (targetEnv === 'production') {
  section('Production Guards');
  
  const guards = manifest.guards || {};
  
  if (guards.productionRequiresExplicitConfirmation) {
    const projectSlug = manifest._meta?.project_slug;
    const requiredValue = `deploy-to-${projectSlug}-production`;
    const confirmation = process.env.CONFIRM_PRODUCTION_DEPLOY;
    
    if (confirmation !== requiredValue) {
      fail('Production deployment confirmation required');
      console.error(`  Set environment variable:`);
      console.error(`  ${c.bold}CONFIRM_PRODUCTION_DEPLOY=${requiredValue}${c.reset}`);
      errorCount++;
    } else {
      pass('Production deployment confirmed');
    }
  }
  
  // Check branch guard
  if (guards.productionAllowedBranches) {
    const currentBranch = require('child_process')
      .execSync('git rev-parse --abbrev-ref HEAD', { encoding: 'utf8' })
      .trim();
    
    const isAllowed = guards.productionAllowedBranches.some(pattern => {
      if (pattern.endsWith('/*')) {
        return currentBranch.startsWith(pattern.slice(0, -2));
      }
      return currentBranch === pattern;
    });
    
    if (!isAllowed) {
      fail(`Branch "${currentBranch}" is not allowed to deploy to production`);
      console.error(`  Allowed branches: ${guards.productionAllowedBranches.join(', ')}`);
      errorCount++;
    } else {
      pass(`Branch "${currentBranch}" is allowed for production`);
    }
  }
}

// ─── Disallowed patterns check ─────────────────────────────────────────────
const guards = manifest.guards || {};
if (guards.disallowedPatterns?.length > 0) {
  section('Disallowed Pattern Check');
  
  // Check if any source files contain hardcoded IDs that should come from manifest
  if (env.firebase?.projectId) {
    try {
      const result = require('child_process').execSync(
        `grep -r "${env.firebase.projectId}" src/ --include="*.ts" --include="*.tsx" --include="*.dart" -l 2>/dev/null || true`,
        { encoding: 'utf8' }
      ).trim();
      
      if (result) {
        warn(`Firebase project ID found hardcoded in source files:`);
        result.split('\n').filter(Boolean).forEach(f => console.warn(`    ${f}`));
        warningCount++;
      } else {
        pass('No hardcoded Firebase project IDs in source files');
      }
    } catch (e) {
      // grep may not be available
    }
  }
}

// ─── Final result ───────────────────────────────────────────────────────────
section('Result');

if (errorCount > 0) {
  console.error(`\n${c.red}${c.bold}✗ VERIFICATION FAILED — ${errorCount} error(s), ${warningCount} warning(s)${c.reset}`);
  console.error(`  Do not proceed until all errors are resolved.\n`);
  process.exit(1);
} else if (warningCount > 0) {
  console.warn(`\n${c.yellow}${c.bold}⚠ VERIFICATION PASSED WITH WARNINGS — ${warningCount} warning(s)${c.reset}`);
  console.log(`  ${c.green}Environment: ${c.bold}${env.label || targetEnv}${c.reset}`);
  console.log(`  ${c.green}Project: ${c.bold}${manifest._meta?.project_name}${c.reset}\n`);
  process.exit(0);
} else {
  console.log(`\n${c.green}${c.bold}✓ VERIFICATION PASSED${c.reset}`);
  console.log(`  Environment: ${c.bold}${env.label || targetEnv}${c.reset}`);
  console.log(`  Project: ${c.bold}${manifest._meta?.project_name}${c.reset}\n`);
  process.exit(0);
}
